/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package university.GUI;

import ftpConnection.FTPUploader;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import university.dao.classes.CoursDAO;
import university.dao.classes.EnseignantDAO;
import university.dao.classes.ModuleDAO;
import university.dao.classes.UserDAO;
import university.entities.Cours;
import university.entities.Enseignant;
import university.entities.Module;
import university.entities.ResponsableModule;
import university.entities.User;

/**
 *
 * @author bechir
 */
public class AjoutCours extends javax.swing.JFrame {
   private String dat;
   private String imgupload;
   private String imgdir;
   private String imagename;
   private String hostDir="public_html/cours/";
    Module module=new Module();
    ModuleDAO moduleDAO=new ModuleDAO();
    List<Module> listm =null;
    public AjoutCours() {
        initComponents();
        setSize(818, 630);
        ModuleDAO mdao=new ModuleDAO();
         listm=mdao.DisplayAllObject();
        
        for (int i = 0; i < listm.size(); i++) {
            jComboBox1.addItem(listm.get(i).getNomModule());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 240, 160, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/valider.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 470, 170, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(220, 310, 140, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/parcouris.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 380, 170, 40);

        jLabel1.setText("path");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 390, 320, 14);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/coursV.png"))); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 120, 170, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/examenB.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(390, 120, 180, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/evalautionB.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(600, 120, 180, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profilB.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(20, 120, 160, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mail (1).png"))); // NOI18N
        getContentPane().add(jButton7);
        jButton7.setBounds(610, 50, 50, 50);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/twit_1.png"))); // NOI18N
        getContentPane().add(jButton8);
        jButton8.setBounds(650, 50, 50, 50);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fb_1.png"))); // NOI18N
        getContentPane().add(jButton9);
        jButton9.setBounds(700, 50, 40, 50);

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(390, 310, 40, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/espaceRespnsable.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 620));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cours cours=new Cours();
        UserDAO userDAO= new UserDAO();
        User user =new User();
        Enseignant enseignant =new Enseignant();
        EnseignantDAO enseignantDAO=new EnseignantDAO();
        CoursDAO coursdao=new CoursDAO();
        ModuleDAO moduledao=new ModuleDAO();
        Module module=new Module();
        Date d=new Date();
        cours.setNomCours(jTextField1.getText());
        cours.setModule(listm.get(jComboBox1.getSelectedIndex()));
        java.util.Date utilDate = new Date();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        cours.setDate(sqlDate);
        cours.setCheminCours("http://ulearn.web44.net/cours/"+imagename);
        enseignant=enseignantDAO.findObjectById(Authentification.idPersonneAutentfie);
        cours.setEnseignant(enseignant);
       // System.out.println(listm.get(jComboBox1.getSelectedIndex()).getIdModule());
        coursdao.insertObject(cours);
        FTPUploader ftpUploader = null;
       try {
           ftpUploader = new FTPUploader();
       } catch (Exception ex) {
           Logger.getLogger(AjoutCours.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {   
           ftpUploader.uploadFile(imgupload, hostDir, "");
             
       } catch (Exception ex) {
           Logger.getLogger(AjoutCours.class.getName()).log(Level.SEVERE, null, ex);
       }
        ftpUploader.disconnect();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showOpenDialog(null);
        File file = jFileChooser.getSelectedFile();
        ImageIcon imageIcon = new ImageIcon(file.getAbsolutePath());
        hostDir+=file.getName();
        imagename=file.getName();
        this.imgupload=file.getAbsolutePath();
        //Image image = imageIcon.getImage(); // transform it 
        //Image newimg = image.getScaledInstance(129, 129,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        jLabel1.setText(file.getAbsolutePath());
        //jLabel1.setIcon(new ImageIcon(newimg));
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EspaceResponsable().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 String nomModule = JOptionPane.showInputDialog("Saissir Le Nouveau Nom Du Module ! ");
        Module module = new Module();
        module.setNomModule(nomModule);
        ModuleDAO dao = new ModuleDAO();
        dao.insertObject(module);
        listm=dao.DisplayAllObject();
        jComboBox1.removeAllItems();
        for (int i = 0; i < listm.size(); i++) {
            jComboBox1.addItem(listm.get(i).getNomModule());
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                this.setVisible(false);
                new GestionExamXXX().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                this.setVisible(false);
                new ConsulterEvaluation().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutCours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
