/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.GUI;

import javax.swing.JOptionPane;
import university.dao.classes.UserDAO;
import university.entities.User;

/**
 *
 * @author LENOVO
 */
public class Authentification extends javax.swing.JFrame {

    
    /**
     * 
     * Creates new form Authentification
     */
    
     public static int idPersonneAutentfie;
     User user;
     UserDAO userDAO = new UserDAO();
     
    public Authentification() {
        initComponents();
        setSize(818, 630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logintxt = new javax.swing.JTextField();
        connecter = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        getContentPane().setLayout(null);

        logintxt.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(logintxt);
        logintxt.setBounds(480, 280, 110, 30);

        connecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/connecter.png"))); // NOI18N
        connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connecterActionPerformed(evt);
            }
        });
        getContentPane().add(connecter);
        connecter.setBounds(270, 410, 170, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sinscrire.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 410, 170, 40);

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(480, 330, 110, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/statistiqB.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 220, 180, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/coursB.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 290, 180, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/authen.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connecterActionPerformed

        // TODO add your handling code here:
        String login=logintxt.getText().toString();
       String password=jPasswordField1.getText().toString();
       
       user= userDAO.findObjectByLoginPassword(login, password);
      //  JOptionPane.showMessageDialog(rootPane, "id= "+user.getId());
        //JOptionPane.showMessageDialog(rootPane, "role= "+user.getRoles());
        
       if(user!=null && user.getLocked()==1){
          idPersonneAutentfie=user.getId();
         JOptionPane.showMessageDialog(rootPane, "Bienvenue "+user.getUsername());

        if(  user.getRoles().equals("Etudiant")){
            this.setVisible(false);
           new EspaceEtudiant().setVisible(true);
           
        }  else if (  user.getRoles().equals("Enseignant")){
            this.setVisible(false);
            new EspaceEnseignant().setVisible(true);
            
        } else if(  user.getRoles().equals("Admin")){
            this.setVisible(false);
            new EspaceAdmin().setVisible(true);
            
        }
        else if(  user.getRoles().equals("ChefEntreprise")){
            this.setVisible(false);
            new EspaceChefEntreprise().setVisible(true);
        }
        else if(  user.getRoles().equals("ResponsableModule")){
            this.setVisible(false);
            new EspaceResponsable().setVisible(true);
        }
        }
        else  {
            JOptionPane.showMessageDialog(rootPane, "Ooops! Vous n'etes pas inscri");
        }
       
    }//GEN-LAST:event_connecterActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Inscription().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      // TODO add your handling code here:
       this.setVisible(false);
       new CoursInternaute().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new JfreeChart().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connecter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField logintxt;
    // End of variables declaration//GEN-END:variables
}
