/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.GUI;

import java.util.Date;
import javax.swing.JOptionPane;
import university.dao.classes.AdminDAO;
import university.dao.classes.CertificationDAO;
import university.entities.Admin;
import university.entities.Certification;

/**
 *
 * @author Safa
 */
public class Cerif extends javax.swing.JFrame {
    Certifmodel certifmodel=new Certifmodel();
    CertificationDAO certifdao = new CertificationDAO ();

    /**
     * Creates new form cerif
     */
    public Cerif() {
        initComponents();
                setSize(818, 630);

        
        certifmodel.setData(certifdao.DisplayAll());
        jTable1.setModel(certifmodel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jduree = new javax.swing.JTextField();
        jnomcertif = new javax.swing.JTextField();
        dateCoursBox = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 250, 375, 88);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/valider.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 440, 174, 40);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Duree");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(11, 70, 34, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 120, 27, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom Certif");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 170, 59, 14);
        jPanel1.add(jduree);
        jduree.setBounds(80, 60, 110, 30);

        jnomcertif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnomcertifActionPerformed(evt);
            }
        });
        jPanel1.add(jnomcertif);
        jnomcertif.setBounds(80, 160, 110, 30);

        dateCoursBox.setBackground(new java.awt.Color(204, 204, 204));
        dateCoursBox.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(dateCoursBox);
        dateCoursBox.setBounds(80, 110, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 200, 200, 290);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supp.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(510, 440, 170, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profilB_1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 110, 130, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/utilisateuB_1.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(170, 110, 130, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stageB.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(320, 110, 150, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/evalautionB_1.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(660, 110, 130, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/certifV_1.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(500, 110, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/espaceAdmin.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Certification certif = new Certification();
       CertificationDAO certifdao =new CertificationDAO();
       Admin admin = new Admin();
       AdminDAO admindao= new AdminDAO();
       admin = admindao.findObjectById(Authentification.idPersonneAutentfie);
       certif.setAdmin(admin);
        java.sql.Date sqlDate = null;
        java.util.Date utilDate;
       certif.setDuree(jduree.getText());
        certif.setNomCertif(jnomcertif.getText());
        

        if (dateCoursBox.getDate() != null) {

            utilDate = dateCoursBox.getDate();
            sqlDate = new java.sql.Date(utilDate.getTime());
            certif.setDateObtention(sqlDate);
            
          certifdao.insertObject(certif);
        certifmodel.setData(certifdao.DisplayAll());
        jTable1.setModel(certifmodel);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Certification c;
        int selectedRowIndex = jTable1.getSelectedRow();
          CertificationDAO certifdao =new CertificationDAO();
        
         if(selectedRowIndex==-1){
            JOptionPane.showMessageDialog(this, "Selectionnez D'abord un Cours du Tableau");
        } else {
        
        c =  certifdao.findById(Integer.parseInt((String) jTable1.getModel().getValueAt(selectedRowIndex,0)));
         
       int reponse=-1;
            reponse=JOptionPane.showConfirmDialog(this,"Vous Voulez Vraiment Supprimer le certif :","Confirmation",JOptionPane.OK_CANCEL_OPTION); 
            if(reponse==JOptionPane.YES_OPTION){
                certifdao.deleteObject(c);
            }
         }
         
 certifmodel.setData(certifdao.DisplayAll());
        jTable1.setModel(certifmodel);
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jnomcertifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnomcertifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnomcertifActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         this.setVisible(false);
        new EspaceAdmin().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
               
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        new ConsulterEvaluationAdmin().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new ConsulterStageAdmin().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cerif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cerif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cerif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cerif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cerif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateCoursBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jduree;
    private javax.swing.JTextField jnomcertif;
    // End of variables declaration//GEN-END:variables
}
