/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.GUI;

import Facebook.ConnexionFacebook;
import TwitterApplication.Loggin;
import TwitterApplication.code;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserAdapter;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserNavigationEvent;
import ftpConnection.FTPUploader;
import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;
import twitter4j.auth.RequestToken;
import twitter4j.conf.Configuration;
import twitter4j.conf.ConfigurationBuilder;
import TwitterApplication.Loggin;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserAdapter;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserNavigationEvent;
import ftpConnection.FTPUploader;
import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import university.dao.classes.UserDAO;
import university.entities.User;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;
import twitter4j.conf.Configuration;
import twitter4j.conf.ConfigurationBuilder;

/**
 *
 * @author LENOVO
 */
public class EspaceEtudiant extends javax.swing.JFrame {

     ConnexionFacebook cnxFacebook=new ConnexionFacebook();
 RequestToken requestToken;
    Twitter twitter ;
   private String dat;
   private String imgupload;
   private String imgdir;
   private String hostDir="public_html/img_user/";
   private String imagename;
    public EspaceEtudiant() {
        initComponents();
        setSize(818, 630);
        UserDAO userDAO = new UserDAO();
        User u = new User();
        u = userDAO.findObjectById(Authentification.idPersonneAutentfie);
        login.setText(u.getUsername());
        motdepasse.setText(u.getPassword());
        nom.setText(u.getNom());
        prenom.setText(u.getPrenom());
        email.setText(u.getEmail());
        ddn.setDate(u.getNaissance());
        sexe.setSelectedItem(u.getSexe());

        try {
            if (u.getCheminImage().equals("")) {
//                u.setCheminImage("http://thecontentwrangler.com/wp-content/uploads/2011/08/User.png");
                ImageIcon imageIcon = new ImageIcon("C:\\Users\\bechir\\Desktop\\final\\university\\src\\image\\images.jpg");
                Image image = imageIcon.getImage(); // transform it 
                Image newimg = image.getScaledInstance(129, 129, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
                jLabel2.setText("");
                jLabel2.setIcon(new ImageIcon(newimg));

            } else {
                ImageIcon imageIcon = new ImageIcon(new URL(u.getCheminImage()));
                Image image = imageIcon.getImage(); // transform it 
                Image newimg = image.getScaledInstance(129, 129, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
                jLabel2.setText("");
                jLabel2.setIcon(new ImageIcon(newimg));
            }

        } catch (MalformedURLException ex) {
            Logger.getLogger(EspaceEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        login = new javax.swing.JTextField();
        motdepasse = new javax.swing.JPasswordField();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        ddn = new com.toedter.calendar.JDateChooser();
        sexe = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profilV_1.png"))); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 120, 130, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/coursB_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(160, 120, 130, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/examenB_1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(300, 120, 130, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/evalautionB_1.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(640, 120, 140, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/x.png"))); // NOI18N
        jPanel1.add(jButton5);
        jButton5.setBounds(750, 60, 40, 40);

        login.setBackground(new java.awt.Color(204, 204, 204));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(220, 200, 120, 30);

        motdepasse.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(motdepasse);
        motdepasse.setBounds(220, 240, 120, 30);

        nom.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(nom);
        nom.setBounds(220, 290, 120, 30);

        prenom.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(prenom);
        prenom.setBounds(220, 330, 120, 30);

        email.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(email);
        email.setBounds(220, 380, 120, 30);

        ddn.setBackground(new java.awt.Color(204, 204, 204));
        ddn.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(ddn);
        ddn.setBounds(220, 430, 120, 30);

        sexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme"}));
        jPanel1.add(sexe);
        sexe.setBounds(220, 470, 120, 30);

        jLabel2.setText("      photo de profil");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(380, 190, 120, 120);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/camera.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(440, 320, 50, 40);

        jButton9.setBackground(new java.awt.Color(102, 51, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/valider.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(390, 490, 170, 40);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stageB.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(460, 120, 150, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fb_1.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(700, 60, 40, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/twit_1.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(650, 60, 40, 40);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mail (1).png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(610, 60, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profliEtudiant.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showOpenDialog(null);
        File file = jFileChooser.getSelectedFile();
        ImageIcon imageIcon = new ImageIcon(file.getAbsolutePath());
        hostDir+=file.getName();
        imagename=file.getName();
        this.imgupload=file.getAbsolutePath();
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(129, 129,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        jLabel2.setText("");
        jLabel2.setIcon(new ImageIcon(newimg));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int x = 0;
        Pattern mail = Pattern.compile("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9-]+)*\\.([a-z]{2,4})$");
        Matcher matcher = mail.matcher(email.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(null, "Invalid Email");
            x = 1;
        }
        String reg = "^([a-zA-Z]+){2}$";
        Pattern nomp = Pattern.compile(reg);
        Matcher matcher1 = nomp.matcher(nom.getText());
        System.out.println(email.getText() + ":" + matcher.matches());
        if (!matcher1.matches()) {
            JOptionPane.showMessageDialog(null, "Invalid nom");
            x = 1;
        }
        Pattern prenomp = Pattern.compile(reg);
        Matcher matcher2 = prenomp.matcher(prenom.getText());
        if (!matcher2.matches()) {
            JOptionPane.showMessageDialog(null, "Invalid prenom");
            x = 1;
        }
        Pattern password = Pattern.compile("((?=.*[a-zA-Z]).{6,})");
        Matcher matcher3 = password.matcher(motdepasse.getText());
        if (!matcher3.matches()) {
            JOptionPane.showMessageDialog(null, "Invalid Password");
            x = 1;
        }
        if (x == 0) {
            User user = new User();
            UserDAO userDAO = new UserDAO();
            user.setEmail(email.getText());
            user.setUsername(login.getText());
            user.setPassword(motdepasse.getText());
            user.setNom(nom.getText());
            user.setPrenom(prenom.getText());

            java.sql.Date sqlDate = null;
            java.util.Date utilDate;

            if (ddn.getDate() != null) {

                utilDate = ddn.getDate();
                sqlDate = new java.sql.Date(utilDate.getTime());
                user.setNaissance(sqlDate);

            }
            user.setSexe(sexe.getSelectedItem().toString());
            user.setRoles("Etudiant");
            user.setCheminImage("");
            if (imagename != null) {
                user.setCheminImage("http://ulearn.web44.net/img_user/" + imagename);
                FTPUploader ftpUploader = null;
                try {
                    ftpUploader = new FTPUploader();
                } catch (Exception ex) {
                    Logger.getLogger(EspaceEtudiant.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
            //FTP server path is relative. So if FTP account HOME directory is "/home/pankaj/public_html/" and you need to upload 
                    // files to "/home/pankaj/public_html/wp-content/uploads/image2/", you should pass directory parameter as "/wp-content/uploads/image2/"

                    ftpUploader.uploadFile(imgupload, hostDir, "");

                } catch (Exception ex) {
                    Logger.getLogger(EspaceEtudiant.class.getName()).log(Level.SEVERE, null, ex);
                }
                ftpUploader.disconnect();
            }
            userDAO.updateObject(user);
            JOptionPane.showMessageDialog(null, "Inscription avec succes", "Ok", 1);

        }
        
        
          
    }//GEN-LAST:event_jButton9ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ExamEtudiant().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CoursEtudiant().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new eval().setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ConsulterStage().setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        cnxFacebook.loginFb();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    ConfigurationBuilder builder = new ConfigurationBuilder();
                    builder.setOAuthConsumerKey("ezJ53uDboGYg34suje0B7i7M3");
                    builder.setOAuthConsumerSecret("3wqDoNsKrvWHCXu8ct6QUmZWsjdKHw9x7VCNNEBwdbF5HTWDtz");
                    Configuration configuration = builder.build();
                    TwitterFactory factory = new TwitterFactory(configuration);
                    twitter = factory.getInstance();
                    requestToken = twitter.getOAuthRequestToken();
                    System.out.println("Got request token.");
                    System.out.println("Request token: " + requestToken.getToken());
                    System.out.println("Request token secret: " + requestToken.getTokenSecret());
                    NativeInterface.open();
                    NativeInterface.initialize();
                    final JFrame authFrame = new JFrame();
                    // Create the JWebBrowser and add the WebBrowserAdapter
                    JPanel webBrowserPanel = new JPanel(new BorderLayout());
                    final JWebBrowser webBrowser = new JWebBrowser();
                    webBrowser.setMenuBarVisible(false);
                    webBrowser.setButtonBarVisible(false);
                    webBrowser.setLocationBarVisible(false);
                    webBrowser.navigate(requestToken.getAuthorizationURL());
                    webBrowser.addWebBrowserListener(new WebBrowserAdapter() {
                        public void locationChanged(WebBrowserNavigationEvent e) {
                            super.locationChanged(e);
                            // Check if first request was not done
                            if (e.getNewResourceLocation().equals("https://api.twitter.com/oauth/authorize")){
                                code c = new code(requestToken,twitter);
                                c.setVisible(true);
                            }
                        }
                    });

                    webBrowserPanel.add(webBrowser,BorderLayout.CENTER);
                    authFrame.add(webBrowserPanel);
                    authFrame.setSize(400, 500);
                    authFrame.setVisible(true);
                } catch (TwitterException ex) {
                    java.util.logging.Logger.getLogger(Loggin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.setVisible(false);
        new mailessai.MailJfram().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspaceEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspaceEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspaceEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspaceEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspaceEtudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ddn;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login;
    private javax.swing.JPasswordField motdepasse;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JComboBox sexe;
    // End of variables declaration//GEN-END:variables
}
