/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.GUI;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import university.dao.classes.EnseignantDAO;
import university.dao.classes.ExamenDAO;
import university.dao.classes.ModuleDAO;
import university.entities.Enseignant;
import university.entities.Examen;
import university.entities.Module;
import university.entities.QuestionExamen;

/**
 *
 * @author LENOVO
 */
public class GestionExamResponsable extends javax.swing.JFrame {

       ModuleDAO moduleDao = new ModuleDAO();
      List<QuestionExamen> listQuest = new ArrayList<>();

    /**
     * Creates new form GestionExam
     */
    public GestionExamResponsable() {
        initComponents();
        setSize(818, 630);
        
        for (int i = 0; i < moduleDao.DisplayAllObject().size(); i++) {
           jComboBox1.addItem(moduleDao.DisplayAllObject().get(i).getIdModule());
 
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        souel = new javax.swing.JTextField();
        textChoix1 = new javax.swing.JTextField();
        textChoix2 = new javax.swing.JTextField();
        TextChoix3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        textChoix4 = new javax.swing.JTextField();
        nextquest = new javax.swing.JButton();
        terminerexam = new javax.swing.JButton();
        Choix3 = new javax.swing.JRadioButton();
        Choix2 = new javax.swing.JRadioButton();
        Choix1 = new javax.swing.JRadioButton();
        Choix4 = new javax.swing.JRadioButton();
        dateCoursBox = new com.toedter.calendar.JDateChooser();
        ComboM = new javax.swing.JComboBox();
        ComboH = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(320, 20, 160, 30);

        jLabel2.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Module");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(240, 20, 60, 20);

        souel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                souelActionPerformed(evt);
            }
        });
        jPanel2.add(souel);
        souel.setBounds(20, 80, 280, 30);
        jPanel2.add(textChoix1);
        textChoix1.setBounds(120, 130, 210, 30);

        textChoix2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textChoix2ActionPerformed(evt);
            }
        });
        jPanel2.add(textChoix2);
        textChoix2.setBounds(120, 180, 210, 30);
        jPanel2.add(TextChoix3);
        TextChoix3.setBounds(120, 230, 210, 30);

        jLabel3.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bareme");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(450, 130, 70, 20);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(540, 180, 70, 20);

        jLabel4.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Durée");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(450, 180, 50, 17);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(560, 470, 73, 23);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(540, 130, 30, 20);

        textChoix4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textChoix4ActionPerformed(evt);
            }
        });
        jPanel2.add(textChoix4);
        textChoix4.setBounds(120, 280, 210, 30);

        nextquest.setText("Next");
        nextquest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextquestActionPerformed(evt);
            }
        });
        jPanel2.add(nextquest);
        nextquest.setBounds(430, 340, 70, 23);

        terminerexam.setText("Valider");
        terminerexam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminerexamActionPerformed(evt);
            }
        });
        jPanel2.add(terminerexam);
        terminerexam.setBounds(540, 340, 65, 23);

        Choix3.setText("C");
        jPanel2.add(Choix3);
        Choix3.setBounds(340, 230, 33, 23);

        Choix2.setText("B");
        jPanel2.add(Choix2);
        Choix2.setBounds(340, 180, 31, 23);

        Choix1.setText("A");
        jPanel2.add(Choix1);
        Choix1.setBounds(340, 140, 33, 23);

        Choix4.setText("D");
        jPanel2.add(Choix4);
        Choix4.setBounds(340, 280, 33, 23);

        dateCoursBox.setBackground(new java.awt.Color(204, 204, 204));
        dateCoursBox.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(dateCoursBox);
        dateCoursBox.setBounds(530, 230, 110, 30);

        ComboM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"}));
        jPanel2.add(ComboM);
        ComboM.setBounds(580, 280, 50, 20);

        ComboH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jPanel2.add(ComboH);
        ComboH.setBounds(510, 280, 50, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 170, 720, 420);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/examenV.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 120, 180, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/coursB.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 120, 170, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/evalautionB.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(600, 120, 180, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profilB.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 120, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/espaceRespnsable.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 180, 720, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void souelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_souelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_souelActionPerformed

    private void textChoix2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textChoix2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textChoix2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                           
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textChoix4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textChoix4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textChoix4ActionPerformed

    private void nextquestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextquestActionPerformed
        // TODO add your handling code here:
 //List<QuestionExamen> listQuest = new ArrayList<QuestionExamen>();

     
     QuestionExamen question1 = new QuestionExamen();
question1.setCorps(souel.getText());
question1.setChoix1(textChoix1.getText());
question1.setChoix2(textChoix2.getText());
question1.setChoix3(TextChoix3.getText());
question1.setChoix4(textChoix4.getText());
question1.setBarem(Integer.parseInt(jTextField6.getText()));
if(Choix1.isSelected()){
    question1.setBonneReponse(textChoix1.getText());
}else 
    if(Choix2.isSelected()){
    question1.setBonneReponse(textChoix2.getText());
}else
        if(Choix3.isSelected()){
    question1.setBonneReponse(TextChoix3.getText());
}else
            if(Choix4.isSelected()){
    question1.setBonneReponse(textChoix4.getText());
            }

listQuest.add(question1);

souel.setText("");
textChoix1.setText("");
textChoix2.setText("");
TextChoix3.setText("");
textChoix4.setText("");
//jTextField8.setText("");

      System.out.println("test1"+listQuest.toString());
      
    }//GEN-LAST:event_nextquestActionPerformed

    private void terminerexamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminerexamActionPerformed
        Examen examen = new Examen();
        examen.setQuestions(listQuest);
        
//        java.util.Date utilDate = new Date();
//        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
//        java.sql.Date sqlDate = null;
//        java.util.Date utilDate;
        
        
//SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
//int year = dateCoursBox.getDate().getYear()+1900;
//int month = dateCoursBox.getDate().getMonth()+1;
//int day = dateCoursBox.getDate().getDay()+22;
int hour =ComboH.getSelectedIndex();
int min=ComboM.getSelectedIndex();
//Calendar cal = Calendar.getInstance();
//cal.set(Calendar.YEAR, year);
//cal.set(Calendar.MONTH, month - 1); // <-- months start
//                                    // at 0.
//cal.set(Calendar.DAY_OF_MONTH, day);
//cal.set(Calendar.HOUR_OF_DAY, hour);
//cal.set(Calendar.MINUTE, min);
//        java.util.Date d=new Date();
//        System.out.println("date actuel: "+sdf.format(d));
//
//java.sql.Date date = new java.sql.Date(cal.getTimeInMillis());
//System.out.println("date saisie: "+sdf.format(date));
//        if (sdf.format(date).equals(sdf.format(d))) {
//            System.out.println("true");
//            
//        }
//        else
//        {
//            System.out.println("false");
//        }

//        if (dateCoursBox.getDate() != null) {
//
//            utilDate = dateCoursBox.getDate();
//            sqlDate = new java.sql.Date(utilDate.getTime());
//            examen.setDate(sqlDate);
//
//        }    
        examen.setHeure(hour);
        examen.setMinute(min);
        
        java.sql.Date sqlDate = null;
        java.util.Date utilDate;
            utilDate = dateCoursBox.getDate();
            sqlDate = new java.sql.Date(utilDate.getTime());
        examen.setDate(sqlDate);
        
        
        examen.setDuree(Integer.parseInt(jTextField7.getText()) );
        
        EnseignantDAO ensDAO = new EnseignantDAO();
        Enseignant enseignant = ensDAO.findObjectById(Authentification.idPersonneAutentfie);
        examen.setEnseignant(enseignant);
   
     Module module = moduleDao.findObjectById((int) jComboBox1.getSelectedItem());
    examen.setModule(module);
    

    ExamenDAO examenDAO = new ExamenDAO();
    examenDAO.insertObject(examen);
              // TODO add your handling code here:
    }//GEN-LAST:event_terminerexamActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ConsulterEvaluation().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CoursResponsable().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EspaceResponsable().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionExamResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionExamResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionExamResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionExamResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionExamResponsable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Choix1;
    private javax.swing.JRadioButton Choix2;
    private javax.swing.JRadioButton Choix3;
    private javax.swing.JRadioButton Choix4;
    private javax.swing.JComboBox ComboH;
    private javax.swing.JComboBox ComboM;
    private javax.swing.JTextField TextChoix3;
    private com.toedter.calendar.JDateChooser dateCoursBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton nextquest;
    private javax.swing.JTextField souel;
    private javax.swing.JButton terminerexam;
    private javax.swing.JTextField textChoix1;
    private javax.swing.JTextField textChoix2;
    private javax.swing.JTextField textChoix4;
    // End of variables declaration//GEN-END:variables
}
