/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.GUI;

import java.sql.Date;
import university.dao.classes.ChefEntrepriseDAO;
import university.dao.classes.StageDAO;
import university.entities.ChefEntreprise;
import university.entities.Stage;

/**
 *
 * @author LENOVO
 */
public class GestionStage extends javax.swing.JFrame {

    StageTableModel stageModel = new StageTableModel();
    Stage stage = new Stage();
     StageDAO stageDao=new StageDAO();

    /**
     * Creates new form GestionStage
     */
    public GestionStage() {
        initComponents();
        setSize(818, 630);
        stageModel.setData(stageDao.DisplayAllObjectById());
        jTable1.setModel(stageModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateCoursBox = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 620));
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 200, 110, 30);

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 250, 110, 30);

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(220, 300, 110, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajout.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 550, 170, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profilB.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 120, 170, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stageV.png"))); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(420, 120, 180, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supp.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(520, 550, 170, 40);

        jLabel2.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom Entreprise");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 200, 120, 20);

        jLabel3.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Domaine");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 247, 80, 30);

        jLabel4.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Durée");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 310, 45, 17);

        jLabel5.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 360, 35, 17);

        jLabel6.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Description");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 410, 90, 30);

        dateCoursBox.setBackground(new java.awt.Color(204, 204, 204));
        dateCoursBox.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(dateCoursBox);
        dateCoursBox.setBounds(220, 350, 110, 30);

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(200, 400, 150, 96);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(360, 210, 400, 170);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modifier.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(293, 550, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/espaceCHef.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(820, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        stage.setNomEntreprise(jTextField1.getText());
        stage.setDomaine(jTextField2.getText());
        stage.setDuree(jTextField3.getText());
        
        java.sql.Date sqlDate = null;
        java.util.Date utilDate;

        if (dateCoursBox.getDate() != null) {

            utilDate = dateCoursBox.getDate();
            sqlDate = new java.sql.Date(utilDate.getTime());
            stage.setDate(sqlDate);

        }
        stage.setDescription(jTextArea1.getText());
        ChefEntreprise chef= new ChefEntreprise();
        ChefEntrepriseDAO chefDao = new ChefEntrepriseDAO();
        chef= chefDao.findObjectById(Authentification.idPersonneAutentfie);
        stage.setChefEntreprise(chef);
        stageDao.insertObject(stage);
        
        stageModel.setData(stageDao.DisplayAllObject());
        jTable1.setModel(stageModel);
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EspaceChefEntreprise().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         if(jTable1.getSelectedRow() !=-1){
            
           int id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
           stage= stageDao.findObjectById(id);
           stageDao.deleteObject(stage);
           
           stageModel.setData(stageDao.DisplayAllObject());
            jTable1.setModel(stageModel);
             
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int select= jTable1.getSelectedRow();
        if(select !=-1){
            Stage s = stageDao.findObjectById(Integer.parseInt((String) jTable1.getModel().getValueAt(select,0)));
            jTextField1.setText(s.getNomEntreprise());
            jTextField2.setText(s.getDomaine());
            jTextField3.setText(s.getDuree());
            dateCoursBox.setDate(s.getDate());
            jTextArea1.setText(s.getDescription());
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int select = jTable1.getSelectedRow();
        if (select != -1) {
            stage = stageDao.findObjectById(Integer.parseInt((String) jTable1.getModel().getValueAt(select, 0)));

            stage.setNomEntreprise(jTextField1.getText());
            stage.setDomaine(jTextField2.getText());
            stage.setDuree(jTextField3.getText());
            java.sql.Date sqlDate = null;
            java.util.Date utilDate;

            if (dateCoursBox.getDate() != null) {

                utilDate = dateCoursBox.getDate();
                sqlDate = new java.sql.Date(utilDate.getTime());
                stage.setDate(sqlDate);

            }
            stage.setDescription(jTextArea1.getText());
            stageDao.updateObject(stage);
            stageModel.setData(stageDao.DisplayAllObjectById());
            jTable1.setModel(stageModel);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionStage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateCoursBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
