/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.GUI;

import ftpConnection.FTPUploader;
import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import university.dao.classes.UserDAO;
import university.entities.User;

/**
 *
 * @author LENOVO
 */
public class Inscription extends javax.swing.JFrame {

        
   private String dat;
   private String imgupload;
   private String imgdir;
   private String hostDir="public_html/img_user/";
   private String imagename;
    /**
     * Creates new form Inscription
     */
    public Inscription() {
        initComponents();
        setSize(818, 630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        dateCoursBox = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 620));
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 190, 120, 30);

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 280, 120, 30);

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(220, 320, 120, 30);

        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(220, 370, 120, 30);

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(220, 240, 120, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "homme","femme" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(220, 460, 120, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Etudiant", "Enseignant", "ChefEntreprise", "ResponsableModule" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(220, 500, 120, 22);

        dateCoursBox.setBackground(new java.awt.Color(204, 204, 204));
        dateCoursBox.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(dateCoursBox);
        dateCoursBox.setBounds(220, 410, 120, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sinscrire.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 550, 170, 40);

        jLabel2.setText("              photo de profil");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 190, 160, 120);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/camera.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(440, 320, 50, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/retour.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 130, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/inscrip.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showOpenDialog(null);
        File file = jFileChooser.getSelectedFile();
        ImageIcon imageIcon = new ImageIcon(file.getAbsolutePath());
        hostDir+=file.getName();
        imagename=file.getName();
        this.imgupload=file.getAbsolutePath();
        Image image = imageIcon.getImage(); // transform it
        Image newimg = image.getScaledInstance(129, 129,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        jLabel2.setText("");
        jLabel2.setIcon(new ImageIcon(newimg));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        User user=new User();
        UserDAO userDAO=new UserDAO();
        user.setUsername(jTextField1.getText());
        user.setPassword(jPasswordField1.getText());
        user.setNom(jTextField2.getText());
        user.setPrenom(jTextField3.getText());
        user.setEmail(jTextField4.getText());
        java.sql.Date sqlDate = null;
        java.util.Date utilDate;

        if (dateCoursBox.getDate() != null) {

            utilDate = dateCoursBox.getDate();
            sqlDate = new java.sql.Date(utilDate.getTime());
            user.setNaissance(sqlDate);

        }             
        user.setSexe(jComboBox1.getSelectedItem().toString());
        user.setRoles(jComboBox2.getSelectedItem().toString());
        user.setCheminImage("http://ulearn.web44.net/img_user/"+imagename);
        
        userDAO.insertObject(user);
        
        FTPUploader ftpUploader = null;
       try {
           ftpUploader = new FTPUploader();
       } catch (Exception ex) {
           Logger.getLogger(EspaceEtudiant.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           //FTP server path is relative. So if FTP account HOME directory is "/home/pankaj/public_html/" and you need to upload 
           // files to "/home/pankaj/public_html/wp-content/uploads/image2/", you should pass directory parameter as "/wp-content/uploads/image2/"
         
           ftpUploader.uploadFile(imgupload, hostDir, "");
             
       } catch (Exception ex) {
           Logger.getLogger(EspaceEtudiant.class.getName()).log(Level.SEVERE, null, ex);
       }
        ftpUploader.disconnect();
        
        JOptionPane.showMessageDialog(null, "votre demande a été envoyé");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Authentification().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateCoursBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
