/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailessai;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JFileChooser;
import java.lang.String;
import javax.swing.JOptionPane;

/**
 *
 * @author chaima
 */


public class MailJfram extends javax.swing.JFrame {

    URL url = null;
    wshop.mail.Mail mail = new wshop.mail.Mail();
    
    
    /**
     * Creates new form MailJfram
     */
    public MailJfram() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextmailsubject = new javax.swing.JTextField();
        jTextMailAddressSender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextMailAddressReceiver = new javax.swing.JTextField();
        jButtonSendMail = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextArea = new javax.swing.JTextArea();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelpieceJointe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 620));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mot de passe");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 270, 130, 22);

        jLabel2.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("de");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 230, 40, 22);

        jLabel4.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("à");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 320, 19, 14);

        jLabel5.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Objet");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 180, 70, 20);

        jLabel6.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contenu");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 400, 100, 22);
        getContentPane().add(jTextmailsubject);
        jTextmailsubject.setBounds(190, 180, 180, 30);
        getContentPane().add(jTextMailAddressSender);
        jTextMailAddressSender.setBounds(190, 230, 180, 30);

        jLabel7.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Piece jointe");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 480, 110, 22);
        getContentPane().add(jTextMailAddressReceiver);
        jTextMailAddressReceiver.setBounds(190, 310, 180, 30);

        jButtonSendMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/envoyer.png"))); // NOI18N
        jButtonSendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendMailActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSendMail);
        jButtonSendMail.setBounds(400, 550, 160, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouterDoc.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 480, 170, 40);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        getContentPane().add(jTextArea);
        jTextArea.setBounds(190, 370, 180, 94);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(190, 270, 180, 30);

        jLabelpieceJointe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/boitemail.png"))); // NOI18N
        getContentPane().add(jLabelpieceJointe);
        jLabelpieceJointe.setBounds(0, 0, 800, 600);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 240, 2, 2);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(210, 500, 34, 14);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 390, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        int option = chooser.showOpenDialog(null);
        if(option == JFileChooser.APPROVE_OPTION){
            try{
                url = chooser.getSelectedFile().toURL();
                System.out.println(url);
                jLabelpieceJointe.setText(url.toString());

            }
            catch(MalformedURLException exception){
                System.out.println("The URL was malformed ... ");

            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendMailActionPerformed
       Mail m=new Mail();
        m.setMailAddressRecipient(jTextMailAddressReceiver.getText());
       m.setPwd(jPasswordField1.getText());
        m.setMailAddressSender(jTextMailAddressSender.getText());
        m.setMailSubject(jTextmailsubject.getText());
        String[] lines = jTextArea.getText().split("\\n");
        String msg="";
        for(String s:lines){
            msg = msg+s;
        }
       

        m.setMailObject(msg);
        JOptionPane.showMessageDialog(rootPane, "mail sent");
        //System.out.println(jTextArearObject.getToolTipText());
        MailConstruction mc = new MailConstruction();
        mc.getMailProperties();
        String s = null;
        if(url!=null){
            s = cleanUrl(url);
        }
        mc.getMailMessage(s, m);
        mc.SendMessage();

    }//GEN-LAST:event_jButtonSendMailActionPerformed

    
    
     public String cleanUrl(URL url){
        
        String s = url.toString();
        System.out.println("Before Clean");
        System.out.println(s);
        String delims = "/";
        String[] tokens = s.split(delims);
        System.out.println("After Clean");
        String mailPart="";
        for (int i=1;i<tokens.length;i++){
            mailPart+=tokens[i]+"\\\\";
        }
        System.out.println(mailPart);
        return mailPart;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MailJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MailJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MailJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MailJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MailJfram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSendMail;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelpieceJointe;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextMailAddressReceiver;
    private javax.swing.JTextField jTextMailAddressSender;
    private javax.swing.JTextField jTextmailsubject;
    // End of variables declaration//GEN-END:variables
}
